"""empty message

Revision ID: 143610a90311
Revises: 926656f74f8a
Create Date: 2021-04-18 00:19:17.441857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '143610a90311'
down_revision = '926656f74f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorito', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorito', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorito', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorito', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
