"""empty message

Revision ID: 85b4fbc727b3
Revises: f3851cfa893b
Create Date: 2021-04-14 01:44:02.620163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b4fbc727b3'
down_revision = 'f3851cfa893b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorito', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorito', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.drop_column('favorito', 'user_id')
    # ### end Alembic commands ###
