"""empty message

Revision ID: 926656f74f8a
Revises: 85b4fbc727b3
Create Date: 2021-04-18 00:17:03.219224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '926656f74f8a'
down_revision = '85b4fbc727b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorito', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorito', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
