"""empty message

Revision ID: f3851cfa893b
Revises: da4caed5a52c
Create Date: 2021-04-14 01:41:44.540350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3851cfa893b'
down_revision = 'da4caed5a52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('birth_year', sa.String(length=250), nullable=False))
    op.add_column('person', sa.Column('eye_color', sa.String(length=250), nullable=False))
    op.add_column('person', sa.Column('gender', sa.String(length=250), nullable=False))
    op.add_column('person', sa.Column('hair_color', sa.String(length=250), nullable=False))
    op.add_column('person', sa.Column('height', sa.String(length=250), nullable=False))
    op.add_column('person', sa.Column('skin_color', sa.String(length=250), nullable=False))
    op.add_column('planet', sa.Column('climate', sa.String(length=250), nullable=False))
    op.add_column('planet', sa.Column('diameter', sa.String(length=250), nullable=False))
    op.add_column('planet', sa.Column('orbital_period', sa.String(length=250), nullable=False))
    op.add_column('planet', sa.Column('population', sa.String(length=250), nullable=False))
    op.add_column('planet', sa.Column('rotation_period', sa.String(length=250), nullable=False))
    op.add_column('planet', sa.Column('terrain', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'terrain')
    op.drop_column('planet', 'rotation_period')
    op.drop_column('planet', 'population')
    op.drop_column('planet', 'orbital_period')
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'climate')
    op.drop_column('person', 'skin_color')
    op.drop_column('person', 'height')
    op.drop_column('person', 'hair_color')
    op.drop_column('person', 'gender')
    op.drop_column('person', 'eye_color')
    op.drop_column('person', 'birth_year')
    # ### end Alembic commands ###
